manager/urls.py
from django.urls import path

from manager.views import (
    index,
    register_user,
    WorkerListView,
    WorkerDetailView,
    WorkerUpdateView,
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskCreateWithProjectView,
    TaskProjectUpdateView,
    TaskDeleteView,
    CompletedTaskListView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    TaskTypeListView,
    TaskTypeDetailView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TeamListView,
    TeamDetailView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    project_completed_true,
    task_completed_true,
    toggle_assign_to_task,
    toggle_assign_to_team,
)

urlpatterns = [
    path("", index, name="index"),
    path("register/", register_user, name="register"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/<int:pk>/task-complete/", task_completed_true, name="task-complete"),
    path(
        "tasks/create/<int:project_pk>/",
        TaskCreateWithProjectView.as_view(),
        name="task-project-create",
    ),
    path(
        "tasks/<int:pk>/update/<int:project_pk>",
        TaskProjectUpdateView.as_view(),
        name="task-update-project",
    ),
    path("tasks/create-task/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/create-task/<int:pk>/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "tasks/completed_tasks/",
        CompletedTaskListView.as_view(),
        name="completed-tasks",
    ),
    path(
        "tasks/<int:pk>/toggle-assign/",
        toggle_assign_to_task,
        name="toggle-task-assign",
    ),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
    path("task_types/", TaskTypeListView.as_view(), name="task-type-list"),
    path("task_types/<int:pk>/", TaskTypeDetailView.as_view(), name="task-type-detail"),
    path("task_types/create/", TaskTypeCreateView.as_view(), name="task-type-create"),
    path(
        "task_types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task_types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path("teams/", TeamListView.as_view(), name="team-list"),
    path(
        "teams/<int:pk>/toggle-assign/",
        toggle_assign_to_team,
        name="toggle-team-assign",
    ),
    path("teams/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path("teams/create/", TeamCreateView.as_view(), name="team-create"),
    path("teams/<int:pk>/update/", TeamUpdateView.as_view(), name="team-update"),
    path("teams/<int:pk>/delete/", TeamDeleteView.as_view(), name="team-delete"),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("projects/create/", ProjectCreateView.as_view(), name="project-create"),
    path(
        "projects/<int:pk>/update/", ProjectUpdateView.as_view(), name="project-update"
    ),
    path(
        "projects/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"
    ),
    path(
        "projects/<int:pk>/project-complete/",
        project_completed_true,
        name="project_completed",
    ),
]

app_name = "manager"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("manager.urls", namespace="manager")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Position(models.Model):
    name = models.CharField(max_length=60, unique=True, default="worker")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(
        Position, on_delete=models.SET_NULL, related_name="workers", null=True
    )

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"
        ordering = ["username"]

    def get_absolute_url(self):
        return reverse("manager:worker-detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"{self.username} ({self.first_name} {self.last_name})"


class Team(models.Model):
    name = models.CharField(max_length=255)
    members = models.ManyToManyField(Worker, related_name="teams")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=600)
    is_completed = models.BooleanField(default=False)
    deadline = models.DateField()
    team = models.ManyToManyField(Team, related_name="projects", blank=True)

    class Meta:
        ordering = ["is_completed", "deadline", "name"]

    def __str__(self):
        return self.name


class TaskType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    PRIORITY_CHOICES = [
        ("Urgent", "Urgent"),
        ("High", "High"),
        ("Medium", "Medium"),
        ("Low", "Low"),
    ]

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(
        max_length=6, choices=PRIORITY_CHOICES, default="Medium"
    )
    task_type = models.ForeignKey(
        TaskType, on_delete=models.SET_NULL, null=True, related_name="tasks"
    )
    project = models.ForeignKey(
        Project, on_delete=models.SET_NULL, null=True, blank=True, related_name="tasks"
    )
    assignees = models.ManyToManyField(Worker, related_name="tasks")

    class Meta:
        ordering = ["deadline", "name", "is_completed"]

    def get_absolute_url(self):
        return reverse("manager:task-detail", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return f"Task: {self.name}, priority of task : {self.priority}"

manager/views.py
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError

from .forms import ContactForm
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from manager.forms import (
    SignUpForm,
    TaskProjectForm,
    WorkerSearchForm,
    TaskSearchForm,
    TaskTypeSearchForm,
    PositionSearchForm,
    PositionForm,
    ProjectForm,
    TeamForm,
    TeamSearchForm,
    ProjectSearchForm,
    TaskForm,
)
from manager.models import Worker, Task, Position, TaskType, Team, Project


@login_required
def index(request):
    """View function for the home page of the site."""
    num_projects = Project.objects.count()
    num_teams = Team.objects.count()
    task_is_done_true = Task.objects.filter(is_completed=True).count()

    context = {
        "num_projects": num_projects,
        "num_teams": num_teams,
        "task_is_done_true": task_is_done_true,
    }

    return render(request, "manager/index.html", context=context)


def register_user(request):
    msg = None
    success = False

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            authenticate(username=username, password=raw_password)
            msg = "User created - please " f'<a href="{reverse("login")}">login</a>.'
            success = True
        else:
            msg = "Form is not valid"
    else:
        form = SignUpForm()

    return render(
        request,
        "registration/register.html",
        {"form": form, "msg": msg, "success": success},
    )


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 5
    template_name = "manager/worker_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = WorkerSearchForm(initial={"username": username})
        return context

    def get_queryset(self):
        queryset = get_user_model().objects.all()
        form = WorkerSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.all().prefetch_related("tasks__task_type")
    template_name = "manager/worker_detail.html"


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    fields = ["username", "first_name", "last_name", "position"]
    template_name = "manager/worker_update.html"

    def get_success_url(self):
        worker_id = self.kwargs["pk"]
        return reverse_lazy("manager:worker-detail", kwargs={"pk": worker_id})


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 5
    template_name = "manager/task_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = (
            Task.objects.all().select_related("task_type").order_by("is_completed")
        )
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    queryset = Task.objects.all().select_related("task_type")
    template_name = "manager/task_detail.html"


class TaskCreateWithProjectView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskProjectForm
    success_url = reverse_lazy("manager:project-detail")
    template_name = "manager/task_project_form.html"

    def get(self, request, project_pk, *args, **kwargs):
        self.project_pk = project_pk
        self.object = None
        return super().get(request, *args, **kwargs)

    def post(self, request, project_pk, *args, **kwargs):
        self.project_pk = project_pk
        return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["project_pk"] = self.project_pk
        return context

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs["project_pk"] = self.project_pk
        return form_kwargs

    def get_success_url(self):
        return reverse("manager:project-detail", kwargs={"pk": self.project_pk})


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("manager:task-list")
    template_name = "manager/task_form.html"


class TaskProjectUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskProjectForm
    template_name = "manager/project_task_update.html"

    def get(self, request, project_pk, *args, **kwargs):
        self.project_pk = project_pk
        self.object = None
        return super().get(request, *args, **kwargs)

    def post(self, request, project_pk, *args, **kwargs):
        self.project_pk = project_pk
        return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["project_pk"] = self.project_pk
        return context

    def get_form_kwargs(self):
        form_kwargs = super().get_form_kwargs()
        form_kwargs["project_pk"] = self.project_pk
        return form_kwargs

    def get_success_url(self):
        return reverse("manager:project-detail", kwargs={"pk": self.project_pk})


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("manager:task-list")
    template_name = "manager/task_form.html"


class CompletedTaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    queryset = Task.objects.filter(is_completed=True)
    paginate_by = 5
    template_name = "manager/completed_task_list.html"


@login_required
def task_completed_true(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if not task.is_completed:
        task.is_completed = True
        task.save()
    return HttpResponseRedirect(reverse_lazy("manager:task-detail", args=[pk]))


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("manager:task-list")
    template_name = "manager/task_confirm_delete.html"


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 5
    template_name = "manager/position_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = PositionSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Position.objects.all()
        form = PositionSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    form_class = PositionForm
    success_url = reverse_lazy("manager:position-list")
    template_name = "manager/position_form.html"


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    form_class = PositionForm
    success_url = reverse_lazy("manager:position-list")
    template_name = "manager/position_form.html"


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("manager:position-list")
    template_name = "manager/position_confirm_delete.html"


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    paginate_by = 5
    context_object_name = "task_type_list"
    template_name = "manager/task_type_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskTypeSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = TaskType.objects.all()
        form = TaskTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = TaskType
    queryset = TaskType.objects.all()
    context_object_name = "task_type_detail"
    template_name = "manager/task_type_detail.html"


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"

templates/manager/completed_task_list.html
{% extends "base-presentation.html" %}
{% block title %}
Completed tasks
{% endblock %}

{% block content %}
  <br><br><br><br>

  <div class="card-body">
  <h1>Completed Tasks!</h1>
  {% for task in task_list %}
  <div class="mb-3"><a href="{% url "manager:task-detail" pk=task.id %}">{{ task.name }}</a></div>
  {% endfor %}

  </div>
{% endblock %}

templates/manager/contact.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/manager/index.html
{% extends "base-presentation.html" %}

{% block title %} Presentation {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}

  <header class="header-2">
    <div class="page-header section-height-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/annie-spratt.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">
              <a class="text-white" target="_blank"
                 href="#">Task Manager</a>
            </h1>
            <p class="lead text-white mt-3">
              Best Task Manager Ever!
              <br />
            </p>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1" countTo="{{ num_projects }}">0</span>+</h1>
                <h5 class="mt-3"><a href="{% url "manager:project-list" %}">Projects</a></h5>
                <p class="text-sm">Create projects with different teams and add tasks as much as you wish</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"> <span id="state2" countTo="{{ num_teams }}">0</span>+</h1>
                <h5 class="mt-3"><a href="{% url "manager:team-list"%}">Teams</a></h5>
                <p class="text-sm">Be a member or create your own team!</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary" id="state3" countTo="{{ task_is_done_true }}">0</h1>
                <h5 class="mt-3"><a href="{% url "manager:completed-tasks" %}">Completed Tasks</a></h5>
                <p class="text-sm">Here we go, don`t stop solving tasks!</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>

{% endblock javascripts %}

templates/manager/position_list.html
{% extends "base-presentation.html" %}
{% block title %}
  Positions
{% endblock %}
{% block content %}
  <div class="card-body">
  <br><br><br><br>
  <h1>
    Position list
    {% include "includes/search_form.html" %}
    <a href="{% url "manager:position-create"%}" class="btn btn-primary float-lg-end">Create New Position</a>
  </h1>
  {% if position_list %}
  <table class="table table-striped">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
  {% for position in position_list %}
    <tr>
      <td>{{ position.id }}</td>
      <td>{{ position.name }}</td>
      <td><a class="btn btn-secondary" href="{% url "manager:position-update" pk=position.id %}">Update</a></td>
      <td><a href="{% url "manager:position-delete" pk=position.id %}" class="btn btn-danger">Delete</a></td>
    </tr>
  {% endfor %}
  </table>
    {% else %}
    No positions at this moment
  {% endif %}
</div>
{% endblock %}

templates/manager/task_confirm_delete.html
{% extends "base-presentation.html" %}
{% block title %}
Delete
{% endblock %}

{% block content %}
  <div class="offset-lg-2">
      <br><br><br><br>
        <div class="col-md-10">
          <div class="card">
            <div class="card-header pb-0">
              <h1 class="text-center">Delete Task?</h1>
            </div>
          <div class="card-body text-center">
             <form action="" method="post">
               {% csrf_token %}
               <input type="submit" value="Yes" class="btn btn-danger">
              </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}

templates/manager/task_list.html
{% extends "base-presentation.html" %}
{% block title %}
  Tasks
{% endblock %}
{% block content %}
  <div class="card-body">
  <br>
  <br>
  <br>
  <br>
  <h2>
      Task List
    {% include "includes/search_form.html" %}
    <a href="{% url "manager:task-create"%}" class="btn btn-primary float-lg-end">Create New Task</a>
    </h2>
  {% if task_list %}
  <table class="table table-striped">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Deadline</th>
        <th>Is completed</th>
        <th>Type</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

    {% for task in task_list %}
    <tr>
        <td>{{ task.id }}</td>
        <td><a href="{{ task.get_absolute_url }}">{{ task.name }} </a></td>
        <td>{{ task.deadline }}</td>
        <td>{% if task.is_completed %}
          Yes
          {% else %}
          No
        {% endif %} </td>
        <td>{{ task.task_type.name }}</td>
        <td><a href="{% url "manager:task-update" pk=task.id %}" class="btn btn-secondary">Update</a></td>
        <td><a href="{% url "manager:task-delete" pk=task.id %}" class="btn btn-danger">Delete</a></td>
  </tr>
  {% endfor %}
    </table>
    {% else %}
    <p>There are no tasks in the service.</p>
  {% endif %}
  </div>
{% endblock %}

templates/manager/team_confirm_delete.html
{% extends "base-presentation.html" %}
{% block title %}
Delete
{% endblock %}

{% block content %}
  <div class="offset-lg-2">
      <br><br><br><br>
    <div class="col-md-10">
      <div class="card">
        <div class="card-header pb-0">
          <h1 class="text-center">Delete team?</h1>
        </div>
          <div class="card-body text-center">
          <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Yes" class="btn btn-danger">
          </form>
          </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/manager/team_detail.html
{% extends "base-presentation.html" %}
{% block title %}
Team
{% endblock %}
{% block content %}
  <br><br><br><br>
  <div class="card-body">
    <h1>Team details</h1>
    <h3 class="text-center">{{ team.name }}</h3>
    <h3>
      Team members:

      {% if team in user.teams.all %}
        <a href="{% url "manager:toggle-team-assign" pk=team.id %}" class="btn btn-danger float-sm-end">
        Delete me from this team
      </a>
      {% else %}
      <a href="{% url "manager:toggle-team-assign" pk=team.id %}" class="btn btn-success float-sm-end">
        Assign me to this team
      </a>
      {% endif %}

    </h3>
    {% for member in team.members.all %}
      <p>Username: {{ member.username }} (position: {{ member.position }})</p>
    {% endfor %}



    <h3>Team's Project{{ team.projects.all|pluralize }}</h3>
    {% if team.projects.all%}
      {% for project in team.projects.all %}
        <p><a href="{% url "manager:team-detail" pk=project.id%}">{{ project.name }}</a></p>
      {% endfor %}
      {% else %}
      No Projects at this moment
    {% endif %}
  </div>
{% endblock %}

templates/manager/team_list.html
{% extends "base-presentation.html" %}
{% block title %}
Teams
{% endblock %}

{% block content %}
  <br><br><br><br>
  <div class="card-body">
    <h1>
      Team List
      {% include "includes/search_form.html" %}
      <a class="btn btn-primary float-lg-end" href="{% url "manager:team-create" %}">Add new Team</a>
    </h1>
    {% if team_list %}

      <table class="table table-striped">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Projects</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
        {% for team in team_list %}
          <tr>
            <td>{{ team.id }}</td>
            <td><a href="{% url "manager:team-detail" pk=team.id %}">{{ team.name }}</a></td>
            <td>
              {% for project in team.projects.all %}
                <p>{{ project.name }}</p>
              {% endfor %}
            </td>
            <td><a class="btn btn-secondary" href="{% url "manager:team-update" pk=team.id %}">Update</a></td>
            <td><a class="btn btn-danger" href="{% url "manager:team-delete" pk=team.id %}">Delete</a></td>
          </tr>
        {% endfor %}


      </table>
      {% else %}
       <p>No Created teams at this moment</p>

    {% endif %}
  </div>
{% endblock %}